Schema fixes
ghga-de/ghga-metadata-schema pull request #136
Opened 2023-08-09 14:20 UTC by mauerk

Fixes issue (if applicable) #

## Proposed Changes

  - sequencing protocol type: flag updated to optional
  - biospecimen slot in sample: flag updated to recommended
  - phenotypic feautre: flag updated to recommended
  - added CV for storage slot
  - added slots for minSCe properties (cDNA read, cDNA read size, cDNA offset)
  - order of linkage slots updated
  - lane_number deprecated
  
## Checks
  - [ ] Builds locally

2023-08-09 14:50 UTC, anandhi-iyappan submitted a review, later dismissed

2023-10-26 12:17 UTC, sbilge commented on src/schema/submission.yaml
> +      cdna_read:
It would be good to separate the slot additions related to single-cell data to another PR?

2023-10-26 12:19 UTC, sbilge requested changes
Can you separate the slots added for single-cell data to another PR?

2023-10-27 07:16 UTC, sbilge commented on src/schema/submission.yaml
> -      - title
Shall we unify this through the model? Like either name the other title slots in different classes as "name", or the "name"s as title.

2023-10-27 07:34 UTC, sbilge requested changes
Clarification of the difference in using title or name and correcting the corresponding slots  are needed.

2023-10-31 09:03 UTC, sbilge approved these changes

2023-10-31 09:22 UTC, merged