Creating class content schemas
ghga-de/ghga-metadata-schema pull request #145
Opened 2024-03-18 10:00 UTC by sbilge

It involves the changes to extract the class relations and to create class content JSON schemas using the main schema.

2024-03-18 15:03 UTC, KerstenBreuer requested changes
Looks good, just a few note. For understanding, this is targeting step iv of the procedure described in the tech spec: https://github.com/ghga-de/epic-docs/blob/main/49-jackal/technical_specification.md#i-schemapack-based-re-implementation-of-the-metadata-model

2024-03-20 12:13 UTC, sbilge commented on src/schemas/File.json
> +            "$ref": "/workspace/src/schemas/ForwardOrReverseEnum",
Yes, that is what I plan to

2024-03-20 14:25 UTC, KerstenBreuer approved these changes
Thanks for addressing the points

2024-03-20 14:25 UTC, KerstenBreuer commented on exclude_config.yaml
> +- Submission
Maybe add newline, could also be done automatically using pre-commit

2024-03-20 19:18 UTC, merged