Updated release schema 0.9.0
ghga-de/ghga-metadata-schema pull request #77
Opened 2022-09-19 14:35 UTC by anandhi-iyappan

Title:
`Updated release schema 0.9.0`

Description:

 ```
 - has_publication removed from Project
  - has_study made as list in Experiment
  - introduced target regions as mandatory in Library preparation protocol
  - Made library preparation kit retail name and manufacturer as optional
  - Deleted has anatomical entity from Biospecimen
  - Deleted has disease from Biospecimen
  - Deleted has phenotypic feature from Biospecimen
  - has_individual made mandatory under Biospecimen
  - Introduced lane number and sample index sequence to Sample
  - Introduced description to Analysis
  - Introduced description as mandatory to Data Access Policy
  - Introduced author, year and journal to Publication
  - Defined slots for author, year, journal, sample lane number, sample index sequence
```

2022-09-20 07:33 UTC, PMenges approved these changes
Reviewed changes to ghga.yaml. No issues found.

2022-09-20 09:07 UTC, galinatremper requested changes

2022-09-20 09:07 UTC, galinatremper commented on src/schema/ghga.yaml
> +  sample lane number:
The same for lane number (Line 2214)

2022-09-21 13:35 UTC, PMenges approved these changes

2022-09-21 13:51 UTC, galinatremper approved these changes

2022-09-21 13:52 UTC, merged