Feature/fix gdev 1636
ghga-de/ghga-metadata-schema pull request #87
Opened 2023-02-22 15:41 UTC by sbilge

Fixes issue (if applicable) #

## Proposed Changes

  -
  -
  -
  
## Checks
  - [ ] Builds locally

2023-02-23 10:35 UTC, KerstenBreuer approved these changes

2023-02-23 10:35 UTC, KerstenBreuer commented on .devcontainer/dev_build
> +make gen-creation-schema-artifacts stage-derived-schemas
End of line missing.

2023-02-23 10:56 UTC, galinatremper requested changes
@sbilge Please check the YAML format, it seems that we have a small indentation problem in base schema.

2023-02-24 08:41 UTC, galinatremper requested changes

2023-02-24 08:41 UTC, galinatremper commented on src/schema/submission_centric_schema.yaml
>      inlined: true
data use permission is not defined. I think we lost it during splitting, because I cannot find it in none of our schemes.

2023-02-24 12:00 UTC, KerstenBreuer approved these changes

2023-02-24 13:17 UTC, merged